spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
      - id: notification-service
        uri: lb://notification-service
        predicates:
        - Path=/notification/**
        filters:
        - RewritePath=/notification/(?<path>.*), /$\{path}
      - id: music-service
        uri: lb://music-service
        predicates:
        - Path=/music/**
        filters:
        - RewritePath=/music/(?<path>.*), /$\{path}
      - id: sprinkler-service
        uri: lb://sprinkler-service
        predicates:
        - Path=/sprinkler/**
        filters:
        - RewritePath=/sprinkler/(?<path>.*), /$\{path}


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
        